### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by QuinLan-SWU** [GuoliangLi-HZAU/ChIA-PET_Tool_V3#2]
Hello,Prof.Li.There was one exception when i run the tool.The details are as follows:
Exception in thread "main" java.lang.ClassCastException: A REGION object expected.
	at LGL.data.REGION.compareTo(REGION.java:86)
	at LGL.data.CLUSTER.sortHeadTail(CLUSTER.java:150)
	at LGL.data.CLUSTER.<init>(CLUSTER.java:102)
	at process.Pet2Cluster1.preCluster(Pet2Cluster1.java:64)
	at process.InteractionCalling.run(InteractionCalling.java:26)
	at process.Main.main(Main.java:104)
##This means that the program stopped at Step5: Interaction Calling and just like follows:
[Mon Oct 21 10:54:53 CST 2019] Step4: Categorization of PETs ...
[Mon Oct 21 10:54:53 CST 2019] start PetClassification ... 
[Mon Oct 21 10:54:53 CST 2019] start loading PETs from /public/home/yhsun/DRN/Hi-C/test/result/result.bedpe.selected.pet.txt
[Mon Oct 21 10:54:53 CST 2019] 0.554681M PETs read from /public/home/yhsun/DRN/Hi-C/test/result/result.bedpe.selected.pet.txt
[Mon Oct 21 10:54:53 CST 2019] Step5: Interaction Calling ...
PS:
Read file <test.sh.e> for stderr output of this job. 
##The command line:
java -jar /public/home/yhsun/opt/biosoft/ChIA-PET_Tool_V3-master/ChIA-PET.jar --mode 1 --fastq1 test_R1.fq --fastq2 test_R2.fq --linker ./linker/linker_long.txt --minimum_linker_alignment_score 14 --GENOME_INDEX /public/home/yhsun/genome/maizeversion36/maize36.fa --GENOME_LENGTH 2.2e9 --CHROM_SIZE_INFO /public/home/yhsun/genome/genomechro/genome_size_2.txt --CYTOBAND_DATA ./chromInfo/maize_cytoBandIdeo.txt --SPECIES 3 --output /public/home/yhsun/DRN/Hi-C/test --prefix result --thread 4

**Comment by ValdemarP267** [comment]
Hi, I am experiencing the same issue
[Fri Apr 03 17:15:06 CEST 2020] Step5: Interaction Calling ...
Exception in thread "main" java.lang.ClassCastException: A REGION object expected.
        at LGL.data.REGION.compareTo(REGION.java:86)
        at LGL.data.CLUSTER.sortHeadTail(CLUSTER.java:150)
        at LGL.data.CLUSTER.<init>(CLUSTER.java:102)
        at process.Pet2Cluster1.preCluster(Pet2Cluster1.java:64)
        at process.InteractionCalling.run(InteractionCalling.java:26)
        at process.Main.main(Main.java:104)
##The command line I run:
java -jar /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/ChIA-PET.jar --mode 0 --fastq1 /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/test_short_1.fastq --fastq2 /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/test_short_2.fastq --linker /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/linker/linker.txt --minimum_linker_alignment_score 8 --GENOME_INDEX /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/GENOME_INDEX/hg19.fa --GENOME_LENGTH 3E9 --CHROM_SIZE_INFO /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/chromInfo/hg19.chromSize.txt --CYTOBAND_DATA /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/chromInfo/hg19_cytoBandIdeo.txt --SPECIES 1 --output /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/test_short --prefix K562 --thread 4

Since this post is few months old has it been resolved?

**Comment by GuoliangLi-HZAU** [comment]
Hi,

We don't think this is a software problem. From the error message, seems that the format of the data set is different from what expected. Please check the data set format. 

Best regards,
Guoliang


----------------Dr. Guoliang Li
College of Informatics, Huazhong Agricultural University
1 Shizishan Jie, Hongshan Qu, Wuhan 430070, China
Tel: 0086-27-87285078
email: guoliang.li@mail.hzau.edu.cn
URL: http://www.guolianglab.org/

李国亮，博士
武汉市洪山区狮子山街1号
华中农业大学信息学院
邮编：430070
电话：027-87285078
实验室网站：http://www.guolianglab.org/

---------- Origin message ----------
>From："ValdemarP267" <notifications@github.com>
>To："GuoliangLi-HZAU/ChIA-PET_Tool_V3" <ChIA-PET_Tool_V3@noreply.github.com>
>Subject：Re: [GuoliangLi-HZAU/ChIA-PET_Tool_V3] Exception (#2)
>Date：2020-04-03 23:27:24Hi, I am experiencing the same issue
[Fri Apr 03 17:15:06 CEST 2020] Step5: Interaction Calling ...
Exception in thread "main" java.lang.ClassCastException: A REGION object expected.
at LGL.data.REGION.compareTo(REGION.java:86)
at LGL.data.CLUSTER.sortHeadTail(CLUSTER.java:150)
at LGL.data.CLUSTER.<init>(CLUSTER.java:102)
at process.Pet2Cluster1.preCluster(Pet2Cluster1.java:64)
at process.InteractionCalling.run(InteractionCalling.java:26)
at process.Main.main(Main.java:104)
##The command line I run:
java -jar /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/ChIA-PET.jar --mode 0 --fastq1 /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/test_short_1.fastq --fastq2 /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/test_short_2.fastq --linker /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/linker/linker.txt --minimum_linker_alignment_score 8 --GENOME_INDEX /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/GENOME_INDEX/hg19.fa --GENOME_LENGTH 3E9 --CHROM_SIZE_INFO /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/chromInfo/hg19.chromSize.txt --CYTOBAND_DATA /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/chromInfo/hg19_cytoBandIdeo.txt --SPECIES 1 --output /mnt/z/Dropbox/Valdemar_WORK/ChIA-PET/ChIA-PET_Tool_V3/test_short --prefix K562 --thread 4

Since this post is few months old has it been resolved?

**Comment by ttian627** [comment]
I have the same problem with ValdemarP267. I used the test short read file downloaded form NCBI and the other files were provided by the  ChIA-PET_Tool_V3.  Could you help us to resolve it ?

**Comment by hcph** [comment]
It's all about the 'CHROM_SIZE_INFO' file, the chromosome name in  this file should be the same with the 'ipet' file, and use 'chr' not 'Chr'. When I do like this, the problem fixed.

**Comment by abhiag2018** [comment]
> It's all about the 'CHROM_SIZE_INFO' file, the chromosome name in this file should be the same with the 'ipet' file, and use 'chr' not 'Chr'. When I do like this, the problem fixed.

@HeChao7021  thanks. Download the new hg19.chromSize.txt from UCSC worked for me on the test short-read data provided above.
