### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by Qi-Yang-Bioinfo** [GuoliangLi-HZAU/ChIA-PET_Tool_V3#3]
Hi Guoliang , I ran into a java exception on sample data test_long, can you offer some help, please?

My command line:
java -jar ChIA-PET.jar --mode 1 --fastq1 test_long_1.fastq --fastq2 test_long_2.fastq --linker linker_long.txt --minimum_linker_alignment_score 14 --GENOME_INDEX ./bwa_index_GRCh38/GRCh38 --GENOME_LENGTH 3E9 --CHROM_SIZE_INFO chrom_GRCh38.sizes --CYTOBAND_DATA ./ref/cytoBandIdeo.txt --SPECIES 1 --output /./Results --prefix test_long --thread 16

the screen output:
[Sun Oct 11 17:52:35 CST 2020] start ChIA-PET analysis
[Sun Oct 11 17:52:35 CST 2020] Step1: Linker filtering ...
[Sun Oct 11 17:53:14 CST 2020] Step2: Mapping to genome ...
[Sun Oct 11 17:55:22 CST 2020] Step3: Removing redundancy ...
[Sun Oct 11 17:55:48 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 45801
[Sun Oct 11 17:55:49 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 17172
[Sun Oct 11 17:55:51 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 33520
[Sun Oct 11 17:55:52 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 14786
[Sun Oct 11 17:55:54 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 25430
[Sun Oct 11 17:55:56 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 27858
[Sun Oct 11 17:55:56 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 5762
[Sun Oct 11 17:55:58 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 25540
[Sun Oct 11 17:56:01 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 41711
[Sun Oct 11 17:56:02 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 6535
[Sun Oct 11 17:56:02 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 8609
[Sun Oct 11 17:56:03 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 8231
[Sun Oct 11 17:56:04 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 13560
[Sun Oct 11 17:56:05 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 9343
[Sun Oct 11 17:56:05 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 5210
[Sun Oct 11 17:56:05 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 2766
[Sun Oct 11 17:56:06 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 15855
[Sun Oct 11 17:56:08 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 15075
[Sun Oct 11 17:56:10 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 19697
[Sun Oct 11 17:56:10 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 7490
[Sun Oct 11 17:56:11 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 7025
[Sun Oct 11 17:56:11 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1878
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 4720
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 197
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 3
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 2
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 2
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 3
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 6
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 6
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 2
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 2
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:12 CST 2020] start MergeSimilarPETs2 ... 
number of pets = 1
[Sun Oct 11 17:56:20 CST 2020] Step4: Categorization of PETs ...
[Sun Oct 11 17:56:20 CST 2020] start PetClassification ... 
[Sun Oct 11 17:56:20 CST 2020] start loading PETs from /media/oxygen/disk1/YangQi/1.ChIA-PET-project/Results/test_long/test_long.bedpe.selected.pet.txt
[Sun Oct 11 17:56:21 CST 2020] 0.363767M PETs read from /media/oxygen/disk1/YangQi/1.ChIA-PET-project/Results/test_long/test_long.bedpe.selected.pet.txt
[Sun Oct 11 17:56:21 CST 2020] Step5: Interaction Calling ...
Exception in thread "main" java.lang.NullPointerException
	at LGL.data.CLUSTER.sortHeadTail(CLUSTER.java:150)
	at LGL.data.CLUSTER.<init>(CLUSTER.java:102)
	at process.Pet2Cluster1.preCluster(Pet2Cluster1.java:64)
	at process.InteractionCalling.run(InteractionCalling.java:26)
	at process.Main.main(Main.java:104)

**Comment by Qi-Yang-Bioinfo** [comment]
update: I got the same error on test_short dataset.

update2: tried different jdk version(14, 11, 8), all got the same error

**Comment by HeChao7021** [comment]
> update: I got the same error on test_short dataset.
> 
> update2: tried different jdk version(14, 11, 8), all got the same error

The same error when running long-reads ChIA-PET, could you please tell me your solution?

**Comment by hahaha12379** [comment]
Hi, I'm having the same problem as you. Can you tell me how you solved it later?Thank you very much!

**Comment by hcph** [comment]
The genome_table you provided may have some problems, you can check whether the chromosome ID is consistent with fasta file, and whether it contains all the chromosome s-------- 原始邮件 --------发件人： Cecilia ***@***.***>日期： 2022年12月28日周三 晚上8:58收件人： GuoliangLi-HZAU/ChIA-PET_Tool_V3 ***@***.***>抄送： HC ***@***.***>, Comment ***@***.***>主    题： Re: [GuoliangLi-HZAU/ChIA-PET_Tool_V3] Exception in thread "main" java.lang.NullPointerException (#3)
Hi, I'm having the same problem as you. Can you tell me how you solved it later?Thank you very much!
